### ISSUE TITLE
error running this preset

### ISSUE THREAD

**Issue by beckend** [STRML/babel-plugin-es2015-maybe-webpack#1]
`babel testbabel.js --presets es2015-maybe-webpack                                     master ✱ ◼
ReferenceError: [BABEL] testbabel.js: Unknown option: /Users/linken/Coding/REACT/project/node_modules/babel-preset-es2015-maybe-webpack/index.js.makeOptions. Check out http://babeljs.io/docs/usage/options/ for more info
    at Logger.error (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:290:20)
at OptionManager.mergeOptions (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:290:20)
    at /Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:371:14
    at /Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:392:24
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.init (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
    at File.initOptions (/Users/linken/.nvm/versions/node/v6.2.2/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:223:65)`

**Comment by beckend** [comment]
However loose mode `es2015-maybe-webpack/loose` works just fine, the README is also wrong with the name `es2015-maybe-loose` does not exist.
